### ISSUE TITLE
Replacing RootTools with RootShell

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#240]
As proposed in [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/236#issuecomment-68106159), @E3V3A found some advantages to switch to [libsuperuser](https://github.com/Chainfire/libsuperuser) by @Chainfire.

>I like the idea to change to use libsuperuser. Chainfire is always on top of these things and the APIs, and general system bugs, so playing along with that, would be an advantage.

Although I like `RootTools`, we currently constantly experience messages like this in our logfiles:

>:third_party:RootTools:compileDebugJavaNote: /home/travis/build/SecUpwN/Android-IMSI-Catcher-Detector/third_party/RootTools/src/main/java/com/stericson/RootTools/internal/RootToolsInternalMethods.java uses or overrides a deprecated API.

With our App getting even more complex in the future, we rely on stable and crisp root functions.

Hope @Stericson won't be sad about our project making the switch over to `libsuperuser`. The way I would like this replacement to be, is that we somehow link our App code to the latest binary from the `libsuperuser` repo to automatically stay to knotch on that (if possible). How to do this? Discuss please.

**Comment by Stericson** [comment]
Sorry for the delay in response, the new years took me away from my machine.

It should stay up to date, I use this in my own applications so I'm pretty good at keeping RootTools/RootShell up to date with the latest changes that come about.

I can look at how you are using things and construct a pull request down the road.

**Comment by SecUpwN** [comment]
>I can look at how you are using things and construct a pull request down the road.

That would be awesome, @Stericson! Please wait with forking our repo until #213 is solved for good.

**Comment by E3V3A** [comment]
Seem that it was just fixed..

**Comment by Stericson** [comment]
Cool, I'll look into this.

I did some basic digging and think you guys could migrate to RootShell which will slim down the code a bit.

I'll work on cloning the project and making certain thats the case.

**Comment by SecUpwN** [comment]
>I'll work on cloning the project and making certain that's the case.

You'll likely have to clone again since #213 was not really fixed yet. But now it should be ~34 MB in size.

**Comment by SecUpwN** [comment]
>I'll work on cloning the project and making certain that's the case.

You'll likely have to clone again since #213 was not really fixed yet. But now it should be ~35 MB in size.

**Comment by Stericson** [comment]
Sounds good, it might be a week or so before I make the pull request. I need to make sure things are good to go before integrating it into your project.

**Comment by SecUpwN** [comment]
>Sounds good, it might be a week or so before I make the pull request. I need to make sure things are good to go before integrating it into your project.

Fair thing. Please fork our project in a week then to have the most current state. Thanks! :+1:

**Comment by SecUpwN** [comment]
This Issue has been **solved** with #265. Awesome work @Stericson, blessings towards your way!
