### ISSUE TITLE
App restarts after Quit contrary to settings

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#246]
The App restarts after a while, even after selecting `Quit` from drawer, contrary to the disabled "**Settings > Persistent Service**". Seem related to GPS use. Perhaps background service is not shutdown properly?

@tobykurien Please have a look. Especially since you did most of the GPS on/off stuff and this seem related somehow.

**Comment by tobykurien** [comment]
Does this bug still occur? If so, how can I replicate it?

**Comment by SecUpwN** [comment]
Does this bug still occur? If so, how can I replicate it?

@tobykurien, as far as I understood it, when turning on GPS and wanting pressing `Quit` after disabling the persistent service, the App does not shut down. But I cannot confirm this bug. @E3V3A, would you please verify that is still valid with our current release version? If not, please tell us here.

**Comment by E3V3A** [comment]
Woot! Now of course the problem doesn't occur! Ok, let's wait and see. I'll close this issue for now, but I just don't see what has changed since last time it happened there have been no code changes as I can tell...

**Comment by d-mariano** [comment]
Perhaps we can kill it via pid?  Some say it to be a nasty thing, but I believe it may work.

**Comment by E3V3A** [comment]
I wonder how *ATM* (above) does it?

**Comment by SecUpwN** [comment]
>I wonder how *ATM* (above) does it?

@E3V3A, I've just written a friendly message to their developers. Hang tight.

**Comment by d-mariano** [comment]
Thank you!  I forgot to introduce myself, I should have done so.   I am quite new to this world of GitHub and developing in general.  

Here's what I was looking at.  pull the pid and assign it to an int, then kill it.  Of course, you could just have this all as one line and just pass the return of myPid() into killProcess() 
int pid = android.os.Process.myPid();
android.os.Process.killProcess(pid);

I have, however, found a more elegant solution.  When quit is selected, an intent is made the the main activity, AIMSICD.  This intent has the flag FLAG_ACTIVITY_TOP_CLEAR set, which will close all activities above the main one before beginning it.  An extra "EXIT" is passed into the intent as well.  In AIMSICD's onCreate() method, the EXIT extra is tested.  If Quit was selected, this would filter the activity to finish().  This solution solves the problem of the service not ending and continuing, as seen in the service bar.  Unfortunately, the app snapshot is still left behind when pulling up recent apps.  If you click on it, the app starts again.  This isn't terrible, but I know when we say quit we mean quit and not hang around in the background apps.

**Comment by tobykurien** [comment]
Guys! Why are we even discussing this? It is standard Android behaviour for an app to still appear in recents and in the app process cache list, even after all it's activities are finished. This isn't a problem and does not mean the app is still running. The only problem is if the service starts up by itself whennit isn't expected to, which doesn't seem to happen anymore, so please close this issue.

**Comment by SecUpwN** [comment]
@tobykurien, I think we've mistaken my answer. The initial Issue that was brought up was that the App restrats itself after quitting with the `Quit` button. What I posted above, was just a thought that we could remove it from the Recents too, since it was brought up by @d-mariano that is still appears there. But the **solution** to the initial problem would likely be using the method mentioned [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/246#issuecomment-69119725).

**Comment by d-mariano** [comment]
I'll get working on that pull request now.  And it's never a bad thing to respect the android.  Firefox, as an example, has the app removed from recent once quit, but keeping it there is definitely not a bad thing.

**Comment by E3V3A** [comment]
We're not respecting Androids here...because Google doesn't respect you.

**Comment by d-mariano** [comment]
Okay, I just made a pull request.  Commit [7e5fea7](https://github.com/d-mariano/Android-IMSI-Catcher-Detector/commit/7e5fea781c844f10f1363483bdbccdf0da74d859) is the one with the correct changes, it was made after [5a6203d](https://github.com/d-mariano/Android-IMSI-Catcher-Detector/commit/5a6203d352ea0cdfb6a9eb8d7d24ee623e7bc988).   I'm not sure if it matters that 2 commits are included in the pull request, but only one (recent one) is relevant.   This is my first pull request, I hope I did that correctly.

**Comment by d-mariano** [comment]
Good point, @E3V3A.

**Comment by d-mariano** [comment]
Before this is closed, is there any other way to have the app quit permanently within the app?  I noticed a block of code describing a quit if the user presses back twice.  If this is so, I should have it call the quit() method I included rather than simply finish()ing.

**Comment by d-mariano** [comment]
I may have found another issue, I notice when testing the solution to this issue that if I do not check and uncheck Persistent Service in Preferences upon a fresh uninstall/reinstall, my solution does not work.   Is anyone experiencing this?

**Comment by He3556** [comment]
yes @d-mariano exactly the same here. I never check and uncheck it before. Now i can close the App :) So this is a bug! thanks

**Comment by d-mariano** [comment]
I found a fix, I have updated my recent comment.

**Comment by tobykurien** [comment]
Looks like someone modified the defaults in settings.XML without updating the code, thus creating that bug. I think the default for 'start on boot' might also be out of sync.

**Comment by tobykurien** [comment]
Another way to exit all app processes is to use Runtime.getInstance().exit(0)

**Comment by SecUpwN** [comment]
>I'm not sure if it matters that 2 commits are included in the pull request, but only one (recent one) is relevant. This is my first pull request, I hope I did that correctly.

@d-mariano, you absolutely did! Thing is, when you open a pull request and notice that further changes are needed, those changes are automatically added to the pull request. Thus, all changes you've made to **your** fork will also be added to **master** once the pull request gets accepted. Cheers!

>Looks like someone modified the defaults in settings.XML without updating the code, thus creating that bug. I think the default for 'start on boot' might also be out of sync.

@tobykurien, I will merge the pull request now. Please check if start on boot is still out of sync.

**Comment by SecUpwN** [comment]
@d-mariano, seems like @ziem also added some funky updates with https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/5a6203d352ea0cdfb6a9eb8d7d24ee623e7bc988. Please comppile the current code and see if this Issue can finally be closed so that we can move on. Thanks!

**Comment by E3V3A** [comment]
This is still present in b13...

**Comment by SecUpwN** [comment]
>This is still present in b13...

Hey @E3V3A, how come you keep forgetting stuff? Too much work? I've told you 5 hours ago that #277 has not been added to b13 and thus of course it keeps reappearing. We'll craft a new version soon. :coffee:

**Comment by E3V3A** [comment]
Can you get me a new build now?

**Comment by SecUpwN** [comment]
>Can you get me a new build now?

Unfortunately, no. My build machine is currently dead. I will talk to @He3556 and send it to you, ok?

**Comment by E3V3A** [comment]
This is still present in b14. No need to close this issue if not verified as fixed...

**Comment by E3V3A** [comment]
@tobykurien I think what you menationed (that I didn't know) about the persistent service setting in xml file, versus the "code" is somehow reversed. There was a short period in last week when I didn't have this bug (#246), but I can't remember for which build that was... Can you also clarify why we need to change the `settings.xml` **and** the code? Because I'm wondering what is the point of having a settings file, if it is not where you change exactly that?

**Comment by SecUpwN** [comment]
@E3V3A, I have just merged a new PR by @d-mariano which should solve this Issue (again) since you were searching for the working commit yesterday. Luckily @d-mariano is a smart guy who found this all by himself! :+1:. Please let there be a few more PRs until we change version numbers again, this Issue should really be **gone for good** with the upcoming internal test version. Cheers!

**Comment by d-mariano** [comment]
The issue was not entirely resolved, as I initially thought.  I have now learned that CellTracker.java did not truly end cell tracking/monitoring in the stop() method.  I have implemented this, I believe(hope) the issue does not return.

**Comment by E3V3A** [comment]
It is fixed!! Thank you very much! :boom:

**Comment by d-mariano** [comment]
My pleasure!

On Mon, Jan 19, 2015 at 10:32 PM, E:V:A <notifications@github.com> wrote:

> Closed #246
> <https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/246>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/246#event-221372996>
> .
>



-- 
-DM
