### ISSUE TITLE
Truncate measured and used Lat/Lon GPS coordinates 

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#325]
There is no reason to have, use or store 16 decimal digits to the Lat/Lon GPS position, ever. Especially since the GPS accuracy is rarely better than 1-10 meters.  Thus, because the approximate [maximum precision](http://en.wikipedia.org/wiki/Decimal_degrees) of decimal Lat/Lon GPS values only varies between 11 to 0 meters, when using 4 decimal places, in going from equator to the pole, we can be happy to truncate all our stored and displayed GPS values to 4 decimal places. 

Justification: If you're standing on the street and can't see an fake BTS antenna within a radius of 10 meters, you will certainly not see it, even if it's next to you.

**Comment by E3V3A** [comment]
Another note: Apparently both GMaps and OSM both use a maximum of 1E7 lat/lon resolution, so we can't expect anything to be accurate for any lat/lon reals with GPS co's of 2+5 digits, even if we had higher resolution.

**Comment by marvinmarnold** [comment]
I didn't look into if the user's actual GPS coordinates are stored and truncating that.

**Comment by E3V3A** [comment]
@marvinmarnold I'm not sure what you mean there...

**Comment by marvinmarnold** [comment]
@E3V3A I don't know if the user's LocationTracker#lastKnownLocation is ultimately stored in a DB somewhere. Maybe its not. If so, should that also be truncated?

**Comment by E3V3A** [comment]
Good question. I'm not sure how to look for this. Certainly if it is used it should be truncated or re-presented. There is no point in storing `12.3456789012345` if its real accuracy is only `12.345678`. In that case I'd rather like to see a value in DB like `12.3456780000000`.

**Comment by E3V3A** [comment]
Only data shown in the `Database Viewer` from the `Imported OCID Data` is truncated. Everywhere else it is still in expanded versions, including details from the `Map Viewer`.

**Comment by marvinmarnold** [comment]
This change #516 in LocationTracker should take care of all the GPS points generated on the device. It is not yet clear to me if the details from Map Viewer are recorded locally or pulled from some API.

**Comment by SecUpwN** [comment]
Thanks for the PR @marvinmarnold, I've just merged it. Please test and respond here, @E3V3A.

**Comment by DJaeger** [comment]
It's now crashing frequently and still don't take care of lacales that use "," as decimal separator as I tried to fix in #510

**Comment by E3V3A** [comment]
I think the issue can be that in some DB tables the GPS is stored as `TEXT` while in others as `REAL` or `FLOAT`...

**Comment by DJaeger** [comment]
They do!
Before only the OCID Download was affected, as the truncateDouble, which is not able to work with "," as decimal separator, is now also used for Cell Tracking, it now also create exceptions on Cell Tracking.

**Comment by E3V3A** [comment]
I can't believe it. Perhaps they also change locale in the sqlite db then?

**Comment by DJaeger** [comment]
No.
It only occures when using String.Format, as this formats to a Locale aware String, which could not be parsed to double by parseDouble as this method requires a dot as decimal separator.

**Comment by E3V3A** [comment]
Can we run truncateDouble though a regex and convert all "," to dots ?

**Comment by DJaeger** [comment]
Please see my new obove mentioned PR (with successful travis build) which does this with native locale aware fuctions.

**Comment by DJaeger** [comment]
The app stil crashes with the same error, also after my fix, so it is not dependant to what I fixed.
The error comes from somewhere else.

```
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.SecUpwN.AIMSICD cmp=com.SecUpwN.AIMSICD/.AIMSICD} from pid 18067
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for activity com.SecUpwN.AIMSICD/.AIMSICD: pid=18473 uid=10644 gids={50644, 3003, 1028, 1015}
E/AndroidRuntime(18473): Process: com.SecUpwN.AIMSICD, PID: 18473
E/AndroidRuntime(18473): 	at com.SecUpwN.AIMSICD.utils.TruncatedLocation.<init>(TruncatedLocation.java:11)
E/AndroidRuntime(18473): 	at com.SecUpwN.AIMSICD.service.LocationTracker.lastKnownLocation(LocationTracker.java:102)
E/AndroidRuntime(18473): 	at com.SecUpwN.AIMSICD.service.LocationTracker.start(LocationTracker.java:56)
E/AndroidRuntime(18473): 	at com.SecUpwN.AIMSICD.service.AimsicdService$1.run(AimsicdService.java:92)
E/AndroidRuntime(18473): 	at com.SecUpwN.AIMSICD.service.AccelerometerMonitor$1.onSensorChanged(AccelerometerMonitor.java:82)
W/ActivityManager(  746):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD
W/ActivityManager(  746): Activity pause timeout for ActivityRecord{4259b320 u0 com.SecUpwN.AIMSICD/.AIMSICD t80 f}
I/ActivityManager(  746): Process com.SecUpwN.AIMSICD (pid 18473) has died.
I/WindowState(  746): WIN DEATH: Window{425dd8a8 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}
W/ActivityManager(  746): Scheduling restart of crashed service com.SecUpwN.AIMSICD/.service.AimsicdService in 1000ms
I/WindowState(  746): WIN DEATH: Window{425e1860 u0 com.SecUpwN.AIMSICD}
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for service com.SecUpwN.AIMSICD/.service.AimsicdService: pid=18680 uid=10644 gids={50644, 3003, 1028, 1015}
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10104000 pkg=com.SecUpwN.AIMSICD cmp=com.SecUpwN.AIMSICD/.AIMSICD} from pid 1143
I/NotificationService(  746): cancelToast pkg=com.SecUpwN.AIMSICD callback=android.app.ITransientNotification$Stub$Proxy@42b07f00
E/AndroidRuntime(18680): Process: com.SecUpwN.AIMSICD, PID: 18680
E/AndroidRuntime(18680): 	at com.SecUpwN.AIMSICD.utils.TruncatedLocation.<init>(TruncatedLocation.java:11)
E/AndroidRuntime(18680): 	at com.SecUpwN.AIMSICD.service.LocationTracker.lastKnownLocation(LocationTracker.java:102)
E/AndroidRuntime(18680): 	at com.SecUpwN.AIMSICD.service.AimsicdService.lastKnownLocation(AimsicdService.java:130)
E/AndroidRuntime(18680): 	at com.SecUpwN.AIMSICD.AIMSICD.selectItem(AIMSICD.java:317)
E/AndroidRuntime(18680): 	at com.SecUpwN.AIMSICD.AIMSICD$DrawerItemClickListener.onItemClick(AIMSICD.java:239)
W/ActivityManager(  746):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD
W/ActivityManager(  746): Activity pause timeout for ActivityRecord{425bc868 u0 com.SecUpwN.AIMSICD/.AIMSICD t81 f}
I/ActivityManager(  746): Process com.SecUpwN.AIMSICD (pid 18680) has died.
W/ActivityManager(  746): Service crashed 2 times, stopping: ServiceRecord{42a8ac88 u0 com.SecUpwN.AIMSICD/.service.AimsicdService}
I/WindowState(  746): WIN DEATH: Window{42d00e58 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.SecUpwN.AIMSICD/.AIMSICD bnds=[588,723][810,973]} from pid 1314
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for activity com.SecUpwN.AIMSICD/.AIMSICD: pid=18881 uid=10644 gids={50644, 3003, 1028, 1015}
E/AndroidRuntime(18881): Process: com.SecUpwN.AIMSICD, PID: 18881
E/AndroidRuntime(18881): 	at com.SecUpwN.AIMSICD.utils.TruncatedLocation.<init>(TruncatedLocation.java:11)
E/AndroidRuntime(18881): 	at com.SecUpwN.AIMSICD.service.LocationTracker.lastKnownLocation(LocationTracker.java:102)
E/AndroidRuntime(18881): 	at com.SecUpwN.AIMSICD.service.LocationTracker.start(LocationTracker.java:56)
E/AndroidRuntime(18881): 	at com.SecUpwN.AIMSICD.service.AimsicdService$1.run(AimsicdService.java:92)
E/AndroidRuntime(18881): 	at com.SecUpwN.AIMSICD.service.AccelerometerMonitor$1.onSensorChanged(AccelerometerMonitor.java:82)
W/ActivityManager(  746):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD
W/ActivityManager(  746): Activity pause timeout for ActivityRecord{425e8cd0 u0 com.SecUpwN.AIMSICD/.AIMSICD t82 f}
I/ActivityManager(  746): Process com.SecUpwN.AIMSICD (pid 18881) has died.
W/ActivityManager(  746): Scheduling restart of crashed service com.SecUpwN.AIMSICD/.service.AimsicdService in 1000ms
I/WindowState(  746): WIN DEATH: Window{42ec7d68 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}
W/NotificationService(  746): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@42eeb920 in package com.SecUpwN.AIMSICD
W/NotificationService(  746): Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@42a7cfe8 in package com.SecUpwN.AIMSICD
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for service com.SecUpwN.AIMSICD/.service.AimsicdService: pid=18944 uid=10644 gids={50644, 3003, 1028, 1015}
E/AndroidRuntime(18944): Process: com.SecUpwN.AIMSICD, PID: 18944
E/AndroidRuntime(18944): 	at com.SecUpwN.AIMSICD.utils.TruncatedLocation.<init>(TruncatedLocation.java:11)
E/AndroidRuntime(18944): 	at com.SecUpwN.AIMSICD.service.LocationTracker.lastKnownLocation(LocationTracker.java:102)
E/AndroidRuntime(18944): 	at com.SecUpwN.AIMSICD.service.LocationTracker.start(LocationTracker.java:56)
E/AndroidRuntime(18944): 	at com.SecUpwN.AIMSICD.service.AimsicdService$1.run(AimsicdService.java:92)
E/AndroidRuntime(18944): 	at com.SecUpwN.AIMSICD.service.AccelerometerMonitor$1.onSensorChanged(AccelerometerMonitor.java:82)
I/ActivityManager(  746): Process com.SecUpwN.AIMSICD (pid 18944) has died.
W/ActivityManager(  746): Service crashed 2 times, stopping: ServiceRecord{42a49c48 u0 com.SecUpwN.AIMSICD/.service.AimsicdService}
I/ActivityManager(  746): START u0 {flg=0x20000004 cmp=com.SecUpwN.AIMSICD/.AIMSICD bnds=[0,555][1080,747] (has extras)} from pid -1
W/ActivityManager(  746): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x20000004 cmp=com.SecUpwN.AIMSICD/.AIMSICD bnds=[0,555][1080,747] (has extras) }
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for activity com.SecUpwN.AIMSICD/.AIMSICD: pid=19214 uid=10644 gids={50644, 3003, 1028, 1015}
E/AndroidRuntime(19214): Process: com.SecUpwN.AIMSICD, PID: 19214
E/AndroidRuntime(19214): 	at com.SecUpwN.AIMSICD.utils.TruncatedLocation.<init>(TruncatedLocation.java:11)
E/AndroidRuntime(19214): 	at com.SecUpwN.AIMSICD.service.LocationTracker.lastKnownLocation(LocationTracker.java:102)
E/AndroidRuntime(19214): 	at com.SecUpwN.AIMSICD.service.AimsicdService.lastKnownLocation(AimsicdService.java:130)
E/AndroidRuntime(19214): 	at com.SecUpwN.AIMSICD.AIMSICD.selectItem(AIMSICD.java:317)
E/AndroidRuntime(19214): 	at com.SecUpwN.AIMSICD.AIMSICD$DrawerItemClickListener.onItemClick(AIMSICD.java:239)
W/ActivityManager(  746):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD
W/ActivityManager(  746): Activity pause timeout for ActivityRecord{4259b320 u0 com.SecUpwN.AIMSICD/.AIMSICD t84 f}
I/ActivityManager(  746): Process com.SecUpwN.AIMSICD (pid 19214) has died.
W/ActivityManager(  746): Scheduling restart of crashed service com.SecUpwN.AIMSICD/.service.AimsicdService in 1000ms
I/WindowState(  746): WIN DEATH: Window{425dd8a8 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for service com.SecUpwN.AIMSICD/.service.AimsicdService: pid=19373 uid=10644 gids={50644, 3003, 1028, 1015}
E/AndroidRuntime(19373): Process: com.SecUpwN.AIMSICD, PID: 19373
E/AndroidRuntime(19373): 	at com.SecUpwN.AIMSICD.utils.TruncatedLocation.<init>(TruncatedLocation.java:11)
E/AndroidRuntime(19373): 	at com.SecUpwN.AIMSICD.service.LocationTracker.lastKnownLocation(LocationTracker.java:102)
E/AndroidRuntime(19373): 	at com.SecUpwN.AIMSICD.service.LocationTracker.start(LocationTracker.java:56)
E/AndroidRuntime(19373): 	at com.SecUpwN.AIMSICD.service.AimsicdService$1.run(AimsicdService.java:92)
E/AndroidRuntime(19373): 	at com.SecUpwN.AIMSICD.service.AccelerometerMonitor$1.onSensorChanged(AccelerometerMonitor.java:82)
I/ActivityManager(  746): Process com.SecUpwN.AIMSICD (pid 19373) has died.
W/ActivityManager(  746): Service crashed 2 times, stopping: ServiceRecord{429eb5b0 u0 com.SecUpwN.AIMSICD/.service.AimsicdService}
W/NotificationService(  746): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@43138100 in package com.SecUpwN.AIMSICD
W/NotificationService(  746): Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@4313e318 in package com.SecUpwN.AIMSICD
I/ActivityManager(  746): START u0 {flg=0x20000004 cmp=com.SecUpwN.AIMSICD/.AIMSICD bnds=[0,555][1080,747] (has extras)} from pid -1
W/ActivityManager(  746): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x20000004 cmp=com.SecUpwN.AIMSICD/.AIMSICD bnds=[0,555][1080,747] (has extras) }
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for activity com.SecUpwN.AIMSICD/.AIMSICD: pid=21394 uid=10644 gids={50644, 3003, 1028, 1015}
I/NotificationService(  746): cancelToast pkg=com.SecUpwN.AIMSICD callback=android.app.ITransientNotification$Stub$Proxy@42c13cd0
I/NotificationService(  746): cancelToast pkg=com.SecUpwN.AIMSICD callback=android.app.ITransientNotification$Stub$Proxy@42c71af0
W/NotificationService(  746): Toast already cancelled. pkg=com.SecUpwN.AIMSICD callback=android.app.ITransientNotification$Stub$Proxy@42c71af0
I/ActivityManager(  746): Killing 21394:com.SecUpwN.AIMSICD/u0a644 (adj 9): remove task
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.SecUpwN.AIMSICD/.AIMSICD bnds=[588,723][810,973]} from pid 1314
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for activity com.SecUpwN.AIMSICD/.AIMSICD: pid=29732 uid=10644 gids={50644, 3003, 1028, 1015}
W/ActivityManager(  746):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD
I/WindowState(  746): WIN DEATH: Window{425b6028 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}
I/ActivityManager(  746): Process com.SecUpwN.AIMSICD (pid 29732) has died.
W/ActivityManager(  746): Scheduling restart of crashed service com.SecUpwN.AIMSICD/.service.AimsicdService in 1000ms
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for service com.SecUpwN.AIMSICD/.service.AimsicdService: pid=29790 uid=10644 gids={50644, 3003, 1028, 1015}
E/AndroidRuntime(29790): Process: com.SecUpwN.AIMSICD, PID: 29790
E/AndroidRuntime(29790): 	at com.SecUpwN.AIMSICD.utils.TruncatedLocation.<init>(TruncatedLocation.java:11)
E/AndroidRuntime(29790): 	at com.SecUpwN.AIMSICD.service.LocationTracker.lastKnownLocation(LocationTracker.java:102)
E/AndroidRuntime(29790): 	at com.SecUpwN.AIMSICD.service.LocationTracker.start(LocationTracker.java:56)
E/AndroidRuntime(29790): 	at com.SecUpwN.AIMSICD.service.AimsicdService$1.run(AimsicdService.java:92)
E/AndroidRuntime(29790): 	at com.SecUpwN.AIMSICD.service.AccelerometerMonitor$1.onSensorChanged(AccelerometerMonitor.java:82)
W/ActivityManager(  746): Process com.SecUpwN.AIMSICD has crashed too many times: killing!
I/ActivityManager(  746): Killing 29790:com.SecUpwN.AIMSICD/u0a644 (adj 0): crash
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.SecUpwN.AIMSICD/.AIMSICD bnds=[588,723][810,973]} from pid 1314
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for activity com.SecUpwN.AIMSICD/.AIMSICD: pid=29842 uid=10644 gids={50644, 3003, 1028, 1015}
W/ActivityManager(  746):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD
I/WindowState(  746): WIN DEATH: Window{42af6660 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}
I/ActivityManager(  746): Process com.SecUpwN.AIMSICD (pid 29842) has died.
W/ActivityManager(  746): Scheduling restart of crashed service com.SecUpwN.AIMSICD/.service.AimsicdService in 1000ms
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for service com.SecUpwN.AIMSICD/.service.AimsicdService: pid=29901 uid=10644 gids={50644, 3003, 1028, 1015}
E/AndroidRuntime(29901): Process: com.SecUpwN.AIMSICD, PID: 29901
E/AndroidRuntime(29901): 	at com.SecUpwN.AIMSICD.utils.TruncatedLocation.<init>(TruncatedLocation.java:11)
E/AndroidRuntime(29901): 	at com.SecUpwN.AIMSICD.service.LocationTracker.lastKnownLocation(LocationTracker.java:102)
E/AndroidRuntime(29901): 	at com.SecUpwN.AIMSICD.service.LocationTracker.start(LocationTracker.java:56)
E/AndroidRuntime(29901): 	at com.SecUpwN.AIMSICD.service.AimsicdService$1.run(AimsicdService.java:92)
E/AndroidRuntime(29901): 	at com.SecUpwN.AIMSICD.service.AccelerometerMonitor$1.onSensorChanged(AccelerometerMonitor.java:82)
W/ActivityManager(  746): Process com.SecUpwN.AIMSICD has crashed too many times: killing!
I/ActivityManager(  746): Killing 29901:com.SecUpwN.AIMSICD/u0a644 (adj 2): crash
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.SecUpwN.AIMSICD/.AIMSICD bnds=[588,723][810,973]} from pid 1314
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for activity com.SecUpwN.AIMSICD/.AIMSICD: pid=29930 uid=10644 gids={50644, 3003, 1028, 1015}
E/AndroidRuntime(29930): Process: com.SecUpwN.AIMSICD, PID: 29930
E/AndroidRuntime(29930): 	at com.SecUpwN.AIMSICD.utils.TruncatedLocation.<init>(TruncatedLocation.java:11)
E/AndroidRuntime(29930): 	at com.SecUpwN.AIMSICD.service.LocationTracker.lastKnownLocation(LocationTracker.java:102)
E/AndroidRuntime(29930): 	at com.SecUpwN.AIMSICD.service.LocationTracker.start(LocationTracker.java:56)
E/AndroidRuntime(29930): 	at com.SecUpwN.AIMSICD.service.AimsicdService$1.run(AimsicdService.java:92)
E/AndroidRuntime(29930): 	at com.SecUpwN.AIMSICD.service.AccelerometerMonitor$1.onSensorChanged(AccelerometerMonitor.java:82)
W/ActivityManager(  746):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD
I/WindowManager(  746): Screenshot max retries 4 of Token{4313bce0 ActivityRecord{4318b8d0 u0 com.SecUpwN.AIMSICD/.AIMSICD t91 f}} appWin=Window{42d01090 u0 Starting com.SecUpwN.AIMSICD} drawState=4
W/ActivityManager(  746): Activity pause timeout for ActivityRecord{4318b8d0 u0 com.SecUpwN.AIMSICD/.AIMSICD t91 f}
W/NotificationService(  746): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@430e0358 in package com.SecUpwN.AIMSICD
I/ActivityManager(  746): Process com.SecUpwN.AIMSICD (pid 29930) has died.
I/WindowState(  746): WIN DEATH: Window{42defd38 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}
W/ActivityManager(  746): Scheduling restart of crashed service com.SecUpwN.AIMSICD/.service.AimsicdService in 3966ms
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for service com.SecUpwN.AIMSICD/.service.AimsicdService: pid=30019 uid=10644 gids={50644, 3003, 1028, 1015}
E/AndroidRuntime(30019): Process: com.SecUpwN.AIMSICD, PID: 30019
E/AndroidRuntime(30019): 	at com.SecUpwN.AIMSICD.utils.TruncatedLocation.<init>(TruncatedLocation.java:11)
E/AndroidRuntime(30019): 	at com.SecUpwN.AIMSICD.service.LocationTracker.lastKnownLocation(LocationTracker.java:102)
E/AndroidRuntime(30019): 	at com.SecUpwN.AIMSICD.service.LocationTracker.start(LocationTracker.java:56)
E/AndroidRuntime(30019): 	at com.SecUpwN.AIMSICD.service.AimsicdService$1.run(AimsicdService.java:92)
E/AndroidRuntime(30019): 	at com.SecUpwN.AIMSICD.service.AccelerometerMonitor$1.onSensorChanged(AccelerometerMonitor.java:82)
I/ActivityManager(  746): Process com.SecUpwN.AIMSICD (pid 30019) has died.
W/ActivityManager(  746): Service crashed 2 times, stopping: ServiceRecord{4344a218 u0 com.SecUpwN.AIMSICD/.service.AimsicdService}
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for broadcast com.SecUpwN.AIMSICD/.receiver.SmsReceiver: pid=17922 uid=10644 gids={50644, 3003, 1028, 1015}
I/ActivityManager(  746): Killing 17922:com.SecUpwN.AIMSICD/u0a644 (adj 15): empty for 1882s
I/ActivityManager(  746): START u0 {act=android.intent.action.EDIT dat=file:///storage/emulated/0/Android/data/me.sheimi.sgit/files/repo/Android-IMSI-Catcher-Detector/app/src/main/java/com/SecUpwN/AIMSICD/utils/TruncatedLocation.java typ=text/x-java flg=0x3000000 cmp=com.aor.droidedit.pro/com.aor.droidedit.DroidEditProActivity} from pid 353
I/ActivityManager(  746): Start proc com.SecUpwN.AIMSICD for broadcast com.SecUpwN.AIMSICD/.receiver.SmsReceiver: pid=20630 uid=10644 gids={50644, 3003, 1028, 1015}
I/ActivityManager(  746): Killing 20630:com.SecUpwN.AIMSICD/u0a644 (adj 15): empty #17
```

**Comment by DJaeger** [comment]
The error is caused in this line (L102):
```
TruncatedLocation location = new TruncatedLocation(lm.getLastKnownLocation(LocationManager.GPS_PROVIDER));
```
Would the following not be enought?
```
TruncatedLocation location = lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);
```
The same for L106:
```
location = new TruncatedLocation(lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER));
```
To:
```
location = lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);
```

**Comment by E3V3A** [comment]
Perhaps TruncatedLocation cannot handle `null` values? 
>  getLastKnownLocation will return null until the callback onLocationChanged() is triggered. This may take several minutes for GPS, even if the sky is clearly visible. If you are indoors it may never run. You have to wait for it to run.

**Comment by DJaeger** [comment]
You are right.
If I let the phone find my position before I start this app it is working great.
Also the OCID Download, I have fixed, is now working.

**Comment by DJaeger** [comment]
We already handled a null return of ```getLastKnownLocation```, but now TruncatedLocation was between the the null location and the null handling, which does not pass throught the null and doesn't take care of it itself.

**Comment by E3V3A** [comment]
@DJaeger I didn't get that. What's going on?

Also, I found [this](http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#setLocale%28java.util.Locale%29) `setLocale` for the DB.

>  public void setLocale (Locale locale)
> Added in API level 1
>
> Sets the locale for this database. Does nothing if this database has the 
> NO_LOCALIZED_COLLATORS flag set or was opened read only.
> Parameters
> locale 	The new locale.
