### ISSUE TITLE
Database locked exception when importing cells from map view

### ISSUE THREAD

**Issue by agilob** [SecUpwN/Android-IMSI-Catcher-Detector#486]
```
06-18 17:10:47.695  20832-20832/com.SecUpwN.AIMSICD I/AIMSICD﹕ DbAdapter:updateOpenCellID: reading file: /storage/emulated/0/Android/data/com.SecUpwN.AIMSICD/files/OpenCellID/opencellid.csv
06-18 17:10:47.715  20832-20832/com.SecUpwN.AIMSICD I/AIMSICD﹕ DbAdapter:updateOpenCellID: OCID CSV size (lines): 9
06-18 17:10:50.448  20832-20832/com.SecUpwN.AIMSICD E/SQLiteDatabase﹕ Error inserting Mnc=10 Lng=-4.07938 avg_range=652 Mcc=234 isGPSexact=1 Type=GSM CellID=39756 Lac=61709 Lat=52.4185 Samples=9 AvgSigStr=-10
    android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
            at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.insertOpenCell(AIMSICDDbAdapter.java:400)
            at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.updateOpenCellID(AIMSICDDbAdapter.java:952)
            at com.SecUpwN.AIMSICD.utils.RequestTask.onPostExecute(RequestTask.java:340)
            at com.SecUpwN.AIMSICD.utils.RequestTask.onPostExecute(RequestTask.java:95)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5158)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
06-18 17:10:53.181  20832-20832/com.SecUpwN.AIMSICD E/SQLiteDatabase﹕ Error inserting Mnc=10 Lng=-4.05107 avg_range=700 Mcc=234 isGPSexact=1 Type=GSM CellID=11363 Lac=61709 Lat=52.41733 Samples=14 AvgSigStr=-10
    android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
            at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.insertOpenCell(AIMSICDDbAdapter.java:400)
            at com.SecUpwN.AIMSICD.adapters.AIMSICDDbAdapter.updateOpenCellID(AIMSICDDbAdapter.java:952)
            at com.SecUpwN.AIMSICD.utils.RequestTask.onPostExecute(RequestTask.java:340)
            at com.SecUpwN.AIMSICD.utils.RequestTask.onPostExecute(RequestTask.java:95)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5158)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by SecUpwN** [comment]
We need to implement #215 first.

**Comment by E3V3A** [comment]
Locked exceptions probably occur because *someone* (something) is trying to use other DB access methods that *raw* sql statements. (I.e. loading an sql buffer with statements to be executed in the end, while having multiple threads with DB access.)

**Comment by E3V3A** [comment]
BTW. @agilob  Did you already try to import from drawer? If you did, the previous import was probably not finished. We need a spinner there, as the "progress bar" for this operation is only binary (0,1) and almost invisible.

**Comment by agilob** [comment]
After installing from F-Droid new users will encounter those errors (#487 #486 #483) - makes application completely useless. AIMSICD crashes on start.

**Comment by SecUpwN** [comment]
>AIMSICD should be downgraded on FDroid or those issues fixed asap and new release published.

As soon as mentioned errors have been fixed, I'll push a fresh build across all stores. Thing is, we need someone who can really do the lifting for us (having our bug-lover @d-mariano in mind)...

**Comment by agilob** [comment]
Those bugs are not fixed. I have the same errors when I compile AIMSICD from master or development branch.

**Comment by SecUpwN** [comment]
>Those bugs are not fixed. I have the same errors when I compile AIMSICD from master or development branch.

I never said that they're fixed. I'll be waiting for @d-mariano to respond, he just re-forked our project.

**Comment by agilob** [comment]
>As soon as mentioned errors have been fixed

ok, I thought you meant those issues. Database storage should be rewritten using ORM ;_;

**Comment by SecUpwN** [comment]
>ok, I thought you meant those issues.

So just to clarify: *This* Issue is currently breaking our build? Which Issues need to be fixed *now*?

**Comment by agilob** [comment]
all mentioned.

**Comment by E3V3A** [comment]
I don't understand why I don't have these issues (AOS 4.2.2)? What's changed?

@agilob 
> Database storage should be rewritten using ORM, none of those problems would exist

Please explain how using ORM would resolve the issues.

**Comment by agilob** [comment]
>Please explain how using ORM would resolve the issues?

All of them are caused by mistakes in raw SQL queries.

>I don't understand why I don't have these issues (AOS 4.2.2)? What's changed?

1. Uninstall AIMSICD
2. reboot device (or clear /tmp)
3. install AIMSICD from FDroid

**Comment by E3V3A** [comment]
F-droid is way behind our dev releases. Ask @SecUpwN for buildozer account.

**Comment by agilob** [comment]
This issue it not solved. It happens both on latest release from fdroid **AND** on development branch from this repository. Whatever...

**Comment by E3V3A** [comment]
reopened... I have no idea how to debug this...

**Comment by DJaeger** [comment]
Can not check this now, as the CSV parsing is currently not working.
Will check this after fixing parsing error.

**Comment by E3V3A** [comment]
Any updates or can we close this?

**Comment by E3V3A** [comment]
> as the CSV parsing is currently not working.

Check that the CSV doesn't have the wrong order in its data. (I recall some similar issues a very long time ago.)

**Comment by E3V3A** [comment]
This is all related to the fact we're not treating DB connections properly. See [these](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/215#issuecomment-118612414) references.

**Comment by agilob** [comment]
Closing because unable to reproduce with 0.1.31 (fdroid)

**Comment by SecUpwN** [comment]
>(still reproducible on 32)

What do you mean, @agilob? The app on F-Droid works, but the debug build doesn't?

**Comment by agilob** [comment]
on 0.1.31 I meant, can't reproduce on 32
